### ISSUE TITLE
client id and client secret.

### ISSUE THREAD

**Issue by BernabePosadas** [team-noob-noob/eWAN#12]
just not to forget. we also need to apply additional layer of authentication for our routes. 

I realized it just yesterday as im programming some login system on my own in node. if we generate token that only require user credentials, would others can also use these to use our routes?.

If we create also include a client secret and id. we may able to limit the use of our routes to clients we trust. 

We can also use a separate login request routes for either session or token based. 

then our routes validates it on our function routes. 

```javascript
app.post("/login/OAuth", async(req, res) => {
    if(!req.body.client_secret || !req.body.client_id){
        return res.status(400).json({error : true, message: "Invalid request", code : 400 });
    }
    else if(req.body.client_id != process.env.client_id || req.body.client_secret != process.env.client_secret){
        return res.status(400).json({error : true, message: "Invalid OAuth credentials", code : 400 });
    }
    var response = await logUser(req);
    if(response.error){
        return res.status(400).json(response);
    }
    return res.status(200).json(response);

});
app.post("/login", async(req, res) => {
    var response = await logUser(req);
    if(response.error){
        return res.status(400).json(response);
    }
    req.session.token = response.access_token;
    return res.status(200).json({success : true});
});
```

**Comment by larongbingo** [comment]
Already finished the authentication. All that's left is build a reusable JWT verification.
