### ISSUE TITLE
launchSettings.json should be ignored in the future commits 

### ISSUE THREAD

**Issue by BernabePosadas** [team-noob-noob/eWAN#18]
it contains our environment variables. needs to be hidden and leave a README.md about its configuration if ever someone will pick up this project

**Comment by larongbingo** [comment]
what if we store them in the actual env instead of a config file, then adding an OR(||) for test/dev purposes
ex
Environment.GetEnvironmentVariable("var") || "default value"

**Comment by BernabePosadas** [comment]
> 
> 
> what if we store them in the actual env instead of a config file, then adding an OR(||) for test/dev purposes
> ex
> Environment.GetEnvironmentVariable("var") || "default value"

that is also possible.

**Comment by larongbingo** [comment]
can we push with that? since after we're in very ultra alpha m8 XD

**Comment by larongbingo** [comment]
Moving the discussion on Enviroment variables on a separate ticket
