### ISSUE TITLE
Use Mediatr to allow for CQRS

### ISSUE THREAD

**Issue by larongbingo** [team-noob-noob/eWAN#4]

**Comment by BernabePosadas** [comment]
hmmm. we should CQRS only when necessary. right now we should follow simplicity first when it became out of control, implement it.

**Comment by larongbingo** [comment]
The problem is that we all noobs, the codebase will get out of control and introduce all kinds kinks. Better to implement it early to reduce backlogs of refactor.

**Comment by BernabePosadas** [comment]
we will learn the concept better if we see the benefits of it by introducing those backlogs. And CQRS should be use only when needed - Martin Fowler one of the Agile Founders

**Comment by BernabePosadas** [comment]
better analyze the entity first b4 we CQRS.
