### ISSUE TITLE
are we really gonna use .net core 3.1? 

### ISSUE THREAD

**Issue by BernabePosadas** [team-noob-noob/eWAN#6]
i checked the .csproject and its on .net core 3.1. might be a good idea to stay at 2.1 for a while. 3.x is not quite stable for some libs in nuget.

**Comment by larongbingo** [comment]
When creating the projects, I didn't bother changing the Dotnet Core version. Also 3.1 is the current LTS for .Net Core, 2.x just died on Dec 23, 2019.
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by larongbingo** [comment]
Derped up, didn't read the End of Support for 2.1 xd

**Comment by BernabePosadas** [comment]
2.1 is LTS XD. i use it for projects so i know hehehehehhe

**Comment by larongbingo** [comment]
Yea, aight gonna Downgrading all four repos to 2.1

**Comment by larongbingo** [comment]
Closing the ticket since the recent commit bumped all projects to netcoreapp2.1
